
- name: Configuration deployment
  hosts: DC1_FABRIC # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 192.168.0.5
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc2MzcxNDI5MTI1MjU5MjY2NjMsImRzbiI6ImF2ZCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3Nzg3NjcxOTksImlhdCI6MTc3ODE2MjUwNSwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiMTNiNzA1YmIxZWM1MzQ3NDk5YmZkZTZmMWQxZjUwOGQyZjFiYjRkZjQ4ODg5OTdhMzVhYjJlOTE4MGI5NjRiZi1rd011VDdfNzBqQjU5VFlUaWNqNWtjUVRYQUFub1BOVElNR1pFbTBYIn0.DmGpVFlF54Gq7cApCwa9t5SPGEeLnhtjfBWHR89paNxt67JTC9NUwi7R3tjiDfp2FwdmafOiiCupAQkNTlSndy4Y4xpOTA7Paqfx2D0n2z1hAl9zKM8rlnXO--fmJCTn0c1yio8RmCKqtA_Dv9Ewpac2s2eXfOAcvDcOx3QIcDvaEr3Sqp0Hrwj6yVrz8VP56H2Gkbuc5-pnX7G7MNyFsC3F4lHGfszr4XBVdVVvPHrtaEOcTBcOG1hmkLBTCUmCWom-DakN0NovTF7T-xx5Q6SjjXRfTlbIcd0lf-miweOqpPAjs-z8JzY2SWqXXmsLoi1RbBmmBXSsboc7FevkxDyh8xmi0FBLEdnU7LFj1d4-aaKQGDwj4znkjl7y8mjRD8OE-JEdzlpmj1uFrowWyDehv3PcC0JIhLBac2ygVjd0_d98nPef_oUAroHDuekdBicVaOYEqdIk2deAkv-Rk_r21V9_2ahGui36rggMJI1tMF2FgbOyYPdYF8B_WpDzI2sJOb1JFT64GiZnPH1hUhSmcCjsB2MgpZ6F3eh5R4U31Gz3Rr0_x3QaJnwDMgeUa7URguyq_gGGLQsR68ZiGAs6pHekhkWsSMeZwNdyTWhWvlzYT04-zNtW1B8DuRmn1rnzBJN6LVwNRzZsI_aBg2SxbagovyU1UhE3_2AQd8M
        cv_verify_certs: false