
- name: Configuration deployment
  hosts: DC1_FABRIC # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 192.168.0.5
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc2MzcxMTczMzE3MDA3MTE2ODcsImRzbiI6ImF2ZCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3Nzg2ODA3OTksImlhdCI6MTc3ODE1NjY3Niwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiY2U5MzMxOTdiZjg2OWQ1ZDk0YTRiNTM0Y2ZjMjkxODc4MjVjYjExMjA4Nzc1ZGNhNzNiZWI1ODAxNjFmNWVhNC0wT0xfMmZFd0QySVd5YlpLRnpxbENpU2F1YmZJb1ROdktyeXpkMW52In0.ebTmpTnP00A2lcuomOJ5mZEj3JkbDPpy5fl4iUuyIj53TPcIx1jIochRA11yjDPLPOaNAVERDSxY6deCPJ1QA7ecN8g-AEFD5CLQjbNaobEbKfDnOoMbEpe4rKcrpTV0l-jdPX-ELZqlrEYGvnP-LNTglNuaxUYP_CtYnxVNF3bA0_1_X6GwqWinh3mn2d0FBuVX2rg9-9lW8h6PiGa6g_AN3kA01r7buq-J1G9Vq9uy9Aujoey25YCXJIKWyX7azEfqRcsLa010ZDWmG0ysx0DgTjTWV9yeM3vRn-qD5fHiZm5mnf41nfwwwqfTftUh8g6lpZDzcqbhBhsetCx-Rl-Iq-YAziLckb4EmfW-VYRGShvE5WoYU8990qZ5SRAaL7FDWX6j65hiGRCNDwaCnYATooHPJW2dNM7pwTYhOrCMWGXbxc8cPlKtDE2cNd61qUkI-o_7U2eS1WjQkp4ZGOAmyZH6LTuC-czeo22OXo6gV1gxaO7NgR6pPa7eHMJ5BJ58YYZ0lUa8O4ItbHFsq0ydi9xe2D_1-R7RH5VG0Q7U_w2rclnEUfC3KZB3CKdqGg3cZZQnQDTOk6xAzVwpUMqh9ArOUw7HsG3PDD6kigS6oDdBZKwo_jJlAiAbI1kaJGgiv8ADQXnVcRGNA3V9yO0uN_bvzKc36mnqzk7uX0o
        cv_verify_certs: false