---
- name: Validate Network State
  hosts: DC1_FABRIC
  connection: httpapi
  gather_facts: true

  tasks:

    - name: validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.anta_runner